layout:
  finger_assignment:
    - [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10]
    - [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10]
    - [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10]
    - [0, 0, 0, 0, 5, 5, 6, 6, 0, 0, 0, 0]

  finger_effort:
    - [5, 3, 2, 1, 2, 7, 7, 2, 1, 2, 3, 5]
    - [5, 2, 1, 0, 0, 5, 5, 0, 0, 1, 2, 5]
    - [8, 4, 2, 2, 1, 8, 8, 1, 2, 2, 4, 8]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  key_size: [1.0, 1.0]

  key_centers:
    - [[0.0, 0.0], [0.0, 1.0], [0.0, 2.0], [0.0, 3.0], [0.0, 4.0], [0.0, 5.0], [0.0, 6.0], [0.0, 7.0], [0.0, 8.0], [0.0, 9.0], [0.0, 10.0], [0.0, 11.0]]
    - [[1.0, 0.0], [1.0, 1.0], [1.0, 2.0], [1.0, 3.0], [1.0, 4.0], [1.0, 5.0], [1.0, 6.0], [1.0, 7.0], [1.0, 8.0], [1.0, 9.0], [1.0, 10.0], [1.0, 11.0]]
    - [[2.0, 0.0], [2.0, 1.0], [2.0, 2.0], [2.0, 3.0], [2.0, 4.0], [2.0, 5.0], [2.0, 6.0], [2.0, 7.0], [2.0, 8.0], [2.0, 9.0], [2.0, 10.0], [2.0, 11.0]]
    - [[3.0, 0.0], [3.0, 1.0], [3.0, 2.0], [3.0, 3.0], [3.0, 4.0], [3.0, 5.0], [3.0, 6.0], [3.0, 7.0], [3.0, 8.0], [3.0, 9.0], [3.0, 10.0], [3.0, 11.0]]

  finger_home_positions:
    1: [1, 1]
    2: [1, 2]
    3: [1, 3]
    4: [1, 4]
    5: [3, 4]
    6: [3, 7]
    7: [1, 7]
    8: [1, 8]
    9: [1, 9]
    10: [1, 10]

# The scales are calculated against all cyanophage layouts, using english and italian corpuses.
# For reference, see branch "feat/generate-optimization-targets"
optimization:
  simulated_annealing:
    init_temp: 150.0
    cooling: 0.998
    stall_accepted: 5000

  # If the field weight is not set, the metric wont be optimized
  targets:
    effort:
      value: 130.0
      scale: 21.24339

    pinky_off_home:
      value: 0.0
      scale: 1.62882

    left_hand_usage:
      value: 50.0
      scale: 3.47652

    finger_usage:
      value:
      scale:
        left_pinky: 1.93048
        left_ring: 1.58789
        left_middle: 3.08812
        left_index: 2.42232
        left_thumb: 3.98745
        right_pinky: 2.47646
        right_ring: 2.60028
        right_middle: 3.20687
        right_index: 3.13870
        right_thumb: 1.52169

    row_usage:
      value:
      scale:
        0: 6.68468
        1: 6.11411
        2: 4.64904
        3: 4.09205

    column_usage:
      value:
      scale:
        0: 0.18226
        1: 1.97208
        2: 1.58789
        3: 3.08812
        4: 4.18511
        5: 2.22832
        6: 2.02181
        7: 3.85511
        8: 3.20687
        9: 2.60028
        10: 2.59892
        11: 0.34410

    bigram_skips:
      value:
        1: 0.0
        2: 0.0
      scale:
        1: 0.58567
        2: 0.26154

    bigram_scissors:
      value:
        1: 0.0
        2: 0.0
      scale:
        1: 0.92127
        2: 1.15803

    bigram_lateral_stretches:
      value:
        pinky: 0.0
        ring: 0.0
        index: 0.0
      scale:
        pinky: 0.64122
        ring: 0.85882
        index: 0.88237

    trigram_skips_same_hand:
      value:
        1: 0.0
        2: 0.0
      scale:
        1: 0.48435
        2: 0.12966

    trigram_skips_alternation:
      value:
        1: 0.0
        2: 0.0
      scale:
        1: 0.59907
        2: 0.19882

    trigram_scissors_same_hand:
      value:
        1: 0.0
        2: 0.0
      scale:
        1: 1.84780
        2: 0.54506

    trigram_scissors_alternation:
      value:
        1: 0.0
        2: 0.0
      scale:
        1: 1.19365
        2: 0.16100

    trigram_lateral_stretches_same_hand:
      value:
        pinky: 0.0
        ring: 0.0
        index: 0.0
      scale:
        pinky: 0.12323
        ring: 0.10839
        index: 0.16829

    trigram_lateral_stretches_alternation:
      value:
        pinky: 0.0
        ring: 0.0
        index: 0.0
      scale:
        pinky: 0.46958
        ring: 0.50452
        index: 0.57241

    trigram_redirects:
      value:
        strong: 0.0
        weak: 0.0
      scale:
        strong: 1.47704
        weak: 0.19694

    trigram_roll_ratio:
      value: 100.0
      scale: 24.02156

    trigram_roll_ratio_bigrams:
      value: 100.0
      scale: 12.03798

    trigram_alternations:
      value: 25.0
      scale: 3.47823
